https://www.googleapis.com/youtube/v3/videos/?key=AIzaSyCB_jwO0CDx7oIHM3wUXTlU0zwiJOh12x8&part=snippet&id=YQHsXMglC9A

###

http://localhost:3000/api/youtube/search?query=hello&part="snippet"&type="video&maxResult=10

###

http://localhost:3000/api/youtube/videos/YQHsXMglC9A?&part="snippet,statistics,player,contentDetails"


###

http://localhost:3000/api/youtube/channels/UComP_epzeKzvBX156r6pm1Q

###

https://www.googleapis.com/youtube/v3/channels/?id=UComP_epzeKzvBX156r6pm1Q&key=AIzaSyCB_jwO0CDx7oIHM3wUXTlU0zwiJOh12x8&part=snippet

###

http://localhost:3000/api/youtube/comments/YQHsXMglC9A

###

http://localhost:3000/api/youtube/channel-videos/UComP_epzeKzvBX156r6pm1Q

###
http://localhost:3000/api/youtube/channel-playlists/UComP_epzeKzvBX156r6pm1Q

###

http://localhost:3000/api/youtube/channel-playlistItems/PLk7ySTbOWfFCZJ44nti0lz7nnMNMilFbs

###

http://localhost:3000/api/youtube/channel-live/UCPdYQsNTgNxyWiPtCCgB5xg

###
http://localhost:3000/api/youtube/channel-search?query=hello&channelId=UC9zX2xZIJ4cnwRsgBpHGvMg

{
    "query": "hello",
    "channelId": "UC9zX2xZIJ4cnwRsgBpHGvMg"
}