https://www.googleapis.com/youtube/v3/videos/?key=AIzaSyCB_jwO0CDx7oIHM3wUXTlU0zwiJOh12x8&part=snippet&id=YQHsXMglC9A

###

http://localhost:5000/api/youtube/search?query=hello&part="snippet"&type="video&maxResult=10

###

http://localhost:5000/api/youtube/videos/YQHsXMglC9A?&part="snippet,statistics,player,contentDetails"


###

http://localhost:5000/api/youtube/channels/UComP_epzeKzvBX156r6pm1Q

###

https://www.googleapis.com/youtube/v3/channels/?id=UComP_epzeKzvBX156r6pm1Q&key=AIzaSyCB_jwO0CDx7oIHM3wUXTlU0zwiJOh12x8&part=snippet

###

http://localhost:5000/api/youtube/comments/YQHsXMglC9A

###

http://localhost:5000/api/youtube/channel-videos/UComP_epzeKzvBX156r6pm1Q

###
http://localhost:5000/api/youtube/channel-playlists/UComP_epzeKzvBX156r6pm1Q

###

http://localhost:5000/api/youtube/channel-playlistItems/PLk7ySTbOWfFCZJ44nti0lz7nnMNMilFbs

###

http://localhost:5000/api/youtube/channel-live/UCPdYQsNTgNxyWiPtCCgB5xg

###
http://localhost:5000/api/youtube/channel-search?query=hello&channelId=UC9zX2xZIJ4cnwRsgBpHGvMg

{
    "query": "hello",
    "channelId": "UC9zX2xZIJ4cnwRsgBpHGvMg"
}

###

GET http://localhost:5000/users

###

GET http://localhost:5000/users/666ca4ea429988986dea6182

###

POST http://localhost:5000/users
Content-Type: application/json

{
    "email": "hello@gmail.com",
    "password": "asdad",
    "firstName": "rostomi",
    "lastName": "rostomi",
    "gender": "Female",
    "day": "26",
    "month": "June",
    "year": "1999"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "nanuka@gmail.com",
    "password": "nanuka"
}

###

POST http://localhost:5000/liked-videos
Content-Type: application/json
Authorization: "Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjZjMzBjODE1NTZhYjVhOTIyMWVmZDIiLCJpYXQiOjE3MTg3MzU3MzcsImV4cCI6MTcxODgyMjEzN30.9TP1xGg-9ETvkofIA0pLWb9YnRNlsxT2-HWx7HpwbqU""

{
    "userID": "666c30c81556ab5a9221efd2",
    "id": "TKaZFDAvzZc"
}

###

POST http://localhost:5000/liked-videos/user-liked-videos
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjZjMzBjODE1NTZhYjVhOTIyMWVmZDIiLCJpYXQiOjE3MTg2NTM1NjAsImV4cCI6MTcxODczOTk2MH0.6hGq2zkIhPZh61f3UfVoqT0y548dw9im2zywHLmL7MM"

{
    "userID": "666c30c81556ab5a9221efd2"
}

###

DELETE http://localhost:5000/liked-videos
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjZjMzBjODE1NTZhYjVhOTIyMWVmZDIiLCJpYXQiOjE3MTg3MTg3MDYsImV4cCI6MTcxODgwNTEwNn0.gioFOdhxHDLzXg3qiKw4ke4tmRflVxgUBT5QatjCJmo"

{
    "userID": "666c30c81556ab5a9221efd2",
    "id": "TiZAVw8snq0"
}

###

POST http://localhost:5000/watch-later-videos
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc5N2ZkNTIxMWE3MWEwMGIzNTJlZTciLCJpYXQiOjE3MTk5MTc4MDMsImV4cCI6MTcyMDAwNDIwM30.d9Vf2nPmvg0ah_130Plgc9bzvA6TORZBJuXtQmw-hZE"

{
    "userID": "66797fd5211a71a00b352ee7",
    "id": "r6Cwze21qLQ"
}

###

POST http://localhost:5000/watch-later-videos/user-watch-later-videos
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc5N2ZkNTIxMWE3MWEwMGIzNTJlZTciLCJpYXQiOjE3MTk5MTc4MDMsImV4cCI6MTcyMDAwNDIwM30.d9Vf2nPmvg0ah_130Plgc9bzvA6TORZBJuXtQmw-hZE"

{
    "userID": "66797fd5211a71a00b352ee7"
}

###

POST http://localhost:5000/subscriptions
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc5N2ZkNTIxMWE3MWEwMGIzNTJlZTciLCJpYXQiOjE3MjAwMTUwMDYsImV4cCI6MTcyMDEwMTQwNn0.b_BtLXK7mNQNbHLSgbstxSnXq_9Sahs7LawU8hO4J3U"

{
    "userID": "66797fd5211a71a00b352ee7",
    "channelID": "UC9zX2xZIJ4cnwRsgBpHGvMg"
}

###

DELETE http://localhost:5000/subscriptions
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc5N2ZkNTIxMWE3MWEwMGIzNTJlZTciLCJpYXQiOjE3MjAwMTUwMDYsImV4cCI6MTcyMDEwMTQwNn0.b_BtLXK7mNQNbHLSgbstxSnXq_9Sahs7LawU8hO4J3U"

{
    "userID": "66797fd5211a71a00b352ee7",
    "channelID": "UC9zX2xZIJ4cnwRsgBpHGvMg"
}

###

POST http://localhost:5000/subscriptions/user-subscriptions
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc5N2ZkNTIxMWE3MWEwMGIzNTJlZTciLCJpYXQiOjE3MjAzNjQ4OTUsImV4cCI6MTcyMDQ1MTI5NX0.1xolEnCo4h4x7vTJP_nlqFztL_ryy30IRc4b861E_dg"

{
    "userID": "66797fd5211a71a00b352ee7"
}

###

POST http://localhost:5000/subscriptions/user-subscription
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc5N2ZkNTIxMWE3MWEwMGIzNTJlZTciLCJpYXQiOjE3MjAzNjUxMjksImV4cCI6MTcyMDQ1MTUyOX0.WhxOlYAYaDeYdzudZMrG34hZAoOQe8ilJVkdoy-WsvI"

{
    "userID": "66797fd5211a71a00b352ee7",
    "channelID": "UC9zX2xZIJ4cnwRsgBpHGvMg"
}